pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Manual Approval') {
            steps {
                input message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed', submitter: 'user'
            }
        }
        stage('Deploy') {
            steps {
               sh './jenkins/scripts/deliver.sh'
            }
            post {
                success {
                    script {
                        sleep(60)  // Menjeda eksekusi pipeline selama 1 menit
                    }
                }
            }
        }
        stage('Cleanup') {
            steps {
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
